### ISSUE TITLE
0.0.4.8 combine drifts out after recovering from unload-interrupt while turning

### ISSUE THREAD

**Issue by prjndigo** [Mogli12/AIVehicleExtension#172] opened 2019-07-23 04:33 UTC
same drifting out as in 0.0.4.5 occurred when interrupted in turn by a overloadable vehicle too close

**Comment by Mogli12** [comment] 2019-07-23 06:51
Sorry, but the problem description is way too short.

**Comment by Mogli12** [comment] 2019-07-30 08:53
Hi,
I do not really understand the problem and I am not able to reproduce it. That is why I close this issue.
If you can add a more details problem description and some screen shots then please reopen it.
BR

**Closed by Mogli12** 2019-07-30 08:53 UTC
