### ISSUE TITLE
0.0.4.8

### ISSUE THREAD

**Issue by MacedonskyAlex** [Mogli12/AIVehicleExtension#170] opened 2019-07-12 17:56 UTC
Combine with a strong bending field is lost. And does not see collision

**Comment by Mogli12** [comment] 2019-07-12 18:21
???

**Comment by prjndigo** [comment] 2019-07-16 21:25
I think he's talking about steep vertical changes, probably the same problem stijnwop/guidanceSteering was having with sudden deflections up and down making the field appear to end.   Both the standard game maps have slopes that have always caused AIV.E. to stop working, like 22? on Felsbrun at the SW corner, I've never had a combine make that turn on AIV.E. in 19

**Comment by Mogli12** [comment] 2019-07-30 08:53
Hi,
I do not really understand the problem and I am not able to reproduce it. That is why I close this issue. 
If you can add a more details problem description and some screen shots then please reopen it.
BR

**Closed by Mogli12** 2019-07-30 08:53 UTC
